---
title: "Snow Covered Area"
author: "AnnaClaire Marley"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Snow covered ARea (km^2)

```{r, include = FALSE}
# load packages 
library(tidyverse)
library(janitor)
library(ggplot2)
```

```{r, include = FALSE}
# set path to source funcitons from data cleaning folder
path_clean = "../Functions/Cleaning/"
path_graph = "../Functions/Graphing/"
```

```{r, echo = FALSE}
# source functions
source(paste0(path_clean, "to_water_week.R")) # for calculating week of water year
source(paste0(path_graph, "graph_season_trend.R"))
```

```{r, echo = FALSE, message = FALSE}
# prism snow
chuska_prism_snow <- read_csv("../Data/chuska_prism_snow.csv")

# snowcourse
snow_course <- read_csv("../Data/nn_snow_course.csv") %>% 
  clean_names() %>% 
  mutate(Date = dmy(date_collected)) %>% 
  mutate(total_depth_mm = conv_unit(total_snow_depth_in, "inch", "mm")) %>% 
  mutate(av_depth_mm = conv_unit(ave_snow_depth_in, "inch", "mm")) %>% 
  mutate(swe_mm = conv_unit(ave_water_content_in, "inch", "mm")) %>% 
  dplyr::select(Date, station_name, swe_mm, av_depth_mm, total_depth_mm) %>% 
  addWaterYear() %>% 
  rename(date = Date)
```

```{r, echo = FALSE}
# km areas of each mountain range:
carrizo_area_km = 339 #km2
chuska_area_km = 4581 #km2
bm_area_km = 1413 #km2
defiance_area_km = 1106 #km2
mt_powell_area_km = 77 #km2
nm_area_km = 96 #km2
nn_area_km = 67636 #km2
```


```{r, echo = FALSE}

# raw snow covered area
sca <- read_csv("../Data/snow_covered_area.csv") %>% 
  clean_names() %>% 
  mutate(date = dmy(date))

sca_tidy <- sca %>% 
  pivot_longer(c(mount_powell:all_mountains), values_to = "sca_km_2", names_to = "region")

chuska_sca <- sca_tidy %>% 
  filter(region == "chuska")

# fraction of snow covered area
sca_fract <- sca %>% 
  mutate(chuska = chuska/chuska_area_km) %>% 
  mutate(defiance_plateau = defiance_plateau/ defiance_area_km) %>% 
  mutate(black_mesa = black_mesa/bm_area_km) %>% 
  mutate(mount_powell = mount_powell/mt_powell_area_km) %>% 
  mutate(carrizo = carrizo/carrizo_area_km) %>% 
  mutate(navajo_mountain = navajo_mountain/nm_area_km) %>% 
  select(date, chuska, defiance_plateau, black_mesa, carrizo, mount_powell, navajo_mountain)
  
sca_fract_tidy <- sca_fract %>% 
  pivot_longer(c(chuska:navajo_mountain), values_to = "fraction", names_to = "region")


```

```{r, echo = FALSE}
# raw sca
sca_tidy %>% 
  filter(!region %in% c("navajo_nation", "all_mountains")) %>% 
  ggplot(aes(x = date, y = sca_km_2)) +
  geom_line(aes(color = region)) +
  labs(
    x = "Year",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Average Weekly Snow Covered Area"
  )+
  scale_x_date(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw() +
  theme(legend.position="bottom", text = element_text(size=14)) 

  ggplot(chuska_sca, aes(x = date, y = sca_km_2)) +
  geom_line() +
  labs(
    x = "Year",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Chuska Mountains Average Weekly Snow Covered Area"
  )+
  scale_x_date(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw() +
  theme(legend.position="bottom", text = element_text(size=14)) 
  
# fraction of mountain covered in snow
  sca_fract_tidy %>% 
  ggplot(aes(x = date, y = fraction)) +
  geom_line(aes(color = region)) +
  labs(
    x = "Year",
    y = "Fraction",
    title = "Fraction of Region Covered in Snow"
  )+
  scale_x_date(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw() +
  theme(legend.position="bottom", text = element_text(size=14)) 

```

```{r, echo = FALSE}

sca_fract_tidy %>% 
  mutate(month = month(date, label = TRUE, abbr = TRUE)) %>% 
  group_by(month) %>% 
  ggplot(aes(x = factor(month, 
                        levels = c("Nov","Dec","Jan", "Feb", "Mar", "Apr")), y = fraction)) +
  geom_boxplot(aes(color = month)) +
  facet_wrap(~region) +
  labs( 
    x = "Month",
    y = "Fraction of SCA",
    title = "Fraction of Area Covered By Snow"
    ) +
  theme_classic()

```


Chuska average weekly snow cover compared to PRISM



```{r, echo = FALSE}

sca_tidy %>% 
  filter(region == "chuska") %>% 
  ggplot(aes(x = date, y = sca_km_2)) +
  geom_col(fill = "steelblue4") +
  labs(
    x = "Year",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Chuska Mountains Average Weekly Snow Covered Area"
  ) +
  scale_x_date(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw() +
  theme(legend.position="bottom", text = element_text(size=14)) 

```

Average SCA for each month

```{r, echo = FALSE}
# raw area
sca_month_av <- chuska_sca %>% 
  mutate(month = month(date, abbr = TRUE, label = TRUE)) %>% 
  rename(Date = date) %>% 
  addWaterYear() %>% 
  group_by(waterYear, month) %>% 
  summarize(sca_km_2 = mean(sca_km_2))

ggplot(sca_month_av, aes(x = waterYear, y = sca_km_2)) +
  geom_col() +
  facet_wrap(~factor(month, c("Nov", "Dec", "Jan", "Feb", "Mar", "Apr"))) +
  labs(
    x = "Water Year",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Chuska Average SCA Each Month"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw()
  
# fraction of mountain covered in snow
sca_month_av_fract <- sca_fract_tidy %>% 
  filter(region == "chuska") %>% 
  mutate(month = month(date, abbr = TRUE, label = TRUE)) %>% 
  rename(Date = date) %>% 
  addWaterYear() %>% 
  group_by(waterYear, month) %>% 
  summarize(fraction = mean(fraction))

ggplot(sca_month_av_fract, aes(x = waterYear, y = fraction)) +
  geom_col() +
  facet_wrap(~factor(month, c("Nov", "Dec", "Jan", "Feb", "Mar", "Apr"))) +
  labs(
    x = "Water Year",
    y = "Fraction",
    title = "Chuska Average Fraction of SCA Each Month"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw()

```


Maximum snow covered area for the Chuskas

```{r, echo = FALSE}

chuska_max_week_sca <- sca_tidy %>% 
  filter(region == "chuska") %>% 
  rename(Date = date) %>% 
  addWaterYear() %>% 
  group_by(waterYear) %>% 
  top_n(1, sca_km_2) %>% 
  mutate(water_week = to_water_week(Date))

ggplot(chuska_max_week_sca, aes(x = waterYear, y = sca_km_2)) +
  geom_col(fill = "brown")


ggplot(chuska_max_week_sca, aes(x = waterYear, y = water_week)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Water Year",
    y = "Water Week",
    title = "Chuska Mountains Timing of Maximum Snow Covered Area"
  ) +
  theme_bw()

graph_season_trend(chuska_max_week_sca, chuska_max_week_sca$water_week,
                   chuska_max_week_sca$waterYear, 
                   title = "Chuska Mountains Timing of Maximum Snow Covered Area", 
                   xlabel = "Water Year",
                   ylabel = "Water Week")  

```

## PRISM and SCA

```{r, echo = FALSE}
# prism average weely accumulated snow
ch_prism_sca <- chuska_prism_snow %>% 
  rename(date = Date) %>% 
  left_join(chuska_sca, by = "date") %>% 
  filter(waterYear >=2000) %>% 
  mutate(prism_snow_m_accum = conv_unit(prism_snow_mm_accum, "mm", "m") )
 

ggplot(ch_prism_sca, aes(x = date, y= sca_km_2/100)) +
  geom_col(fill = "grey62", width = 4) +
  labs(
    x = "Year",
    y = bquote("Snow Covered Area " (x10^2,km^2)),
    title = "Chuska Snow Covered Area and PRISM Estimated Snowfall Accumulation"
  ) +
  geom_line(aes(y = prism_snow_m_accum), color = "#1219cc") +
  scale_x_date(expand = c(0,0)) +
  scale_y_continuous(
          sec.axis = sec_axis(~., "PRISM accumulated snow (m)"),
          expand = c(0,0)
        )+
theme_bw() +
         theme(axis.line.y.right = element_line(color = "#1219cc"),
                axis.text.y.right = element_text(color = "#1219cc"),
                axis.title.y.right = element_text(color = "#1219cc")) 
  
```



```{r, echo = FALSE}

ch_max_prism_sca <- chuska_prism_snow %>% 
  group_by(waterYear) %>% 
  top_n(1, prism_snow_mm_accum) %>% 
  top_n(1, Date) %>% 
  ungroup() %>% 
  mutate(waterYear = replace_na(waterYear, "2000")) %>% 
  mutate(waterYear = as.integer(waterYear)) %>% 
  select(waterYear, prism_snow_mm_accum) %>% 
  left_join(chuska_max_week_sca, by = "waterYear") %>% 
  filter(waterYear > 2000)


ggplot(ch_max_prism_sca, aes(x = sca_km_2, y = prism_snow_mm_accum/1000)) +
  geom_point(aes(color = waterYear)) +
  geom_smooth(method= "lm", se = FALSE) +
  labs(
    x = bquote("Snow Covered Area " (km^2)),
    y = "PRISM Estimated Accumulated Snowfall (m)",
    title = "Maximum SCA and PRISM Accumulated Snowfall Each Winter"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw()

summary(lm(ch_max_prism_sca$prism_snow_mm_accum ~ ch_max_prism_sca$sca_km_2))
  
```

MAX SNOTEL SWE and Chuska SCA

```{r, echo = FALSE}
# read in whiskey creek snotel data
wc_snotel <- read_csv("../Data/wc_snotel.csv") %>% 
  clean_names() %>% 
  mutate(swe_m = conv_unit(swe_mm, "mm", "m")) %>% 
  mutate(Date = date) %>% 
  addWaterYear()

bs_snotel <- read_csv("../Data/bs_snotel.csv") %>% 
  clean_names() %>% 
  mutate(swe_m = conv_unit(swe_mm, "mm", "m"))%>% 
  mutate(Date = date) %>% 
  addWaterYear() %>% 
  left_join()



```
```{r, echo = FALSE}

# whiskey creek
ch_max_wc_snotel_sca <- wc_snotel %>% 
  group_by(waterYear) %>% 
  top_n(1, swe_m) %>% 
  top_n(1, Date) %>% 
  filter(waterYear > 2009) %>% 
  ungroup() %>% 
  select(waterYear, swe_m) %>% 
  left_join(chuska_max_week_sca, by = "waterYear")  %>% 
  mutate(snotel_station = "Whiskey Creek")

ch_max_wc_snotel_sca %>% 
  mutate(waterYear = as.integer(waterYear)) %>% 
ggplot( aes(x = swe_m, y = sca_km_2)) +
  geom_point(aes(color = waterYear)) +
  geom_smooth(method= "lm", se = FALSE) +
  scale_color_gradient(labels = c(2010, 2012, 2015, 2017, 2020)) +
  labs(
    x = "SNOTEL SWE (m)",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Whiskey Creek Max SNOTEL SWE and Chuska SCA",
    color = "Water Year"
  ) +
  theme_bw()

# beaver spring
ch_max_bs_snotel_sca <- bs_snotel %>% 
  group_by(waterYear) %>% 
  top_n(1, swe_m) %>% 
  top_n(1, Date) %>% 
  filter(waterYear > 2009) %>% 
  ungroup() %>% 
  select(waterYear, swe_m) %>% 
  left_join(chuska_max_week_sca, by = "waterYear") %>% 
  mutate(snotel_station = "Beaver Spring")

ch_max_bs_snotel_sca %>% 
  mutate(waterYear = as.integer(waterYear)) %>% 
ggplot( aes(x = swe_m, y = sca_km_2)) +
  geom_point(aes(color = waterYear)) +
  geom_smooth(method= "lm", se = FALSE) +
  scale_color_gradient(labels = c(2010, 2012, 2015, 2017, 2020)) +
  labs(
    x = "SNOTEL SWE (m)",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Beaver Spring Max SNOTEL SWE and Chuska SCA",
    color = "Water Year"
  ) +
  theme_bw()

plot(lm(ch_max_snotel_sca$sca_km_2 ~ ch_max_snotel_sca$swe_m))
cor.test(ch_max_snotel_sca$sca_km_2, ch_max_snotel_sca$swe_m, method = "spearman")

# whiskey creek and beaver springs max swe and SCA
ch_max_sca_wc_bs_snotel <- rbind(ch_max_wc_snotel_sca, ch_max_bs_snotel_sca) %>% 
  mutate(waterYear = as.integer(waterYear))

ggplot(ch_max_sca_wc_bs_snotel, aes(x = swe_m*1000, y = sca_km_2)) +
  geom_point(aes(color = snotel_station)) +
  geom_abline(intercept = 550, slope = 1545.4545, linetype = "dashed") +
  labs(
    x = "SNOTEL SWE (mm)",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Beaver Spring Max SNOTEL SWE and Chuska SCA",
    color = "SNOTEL Station"
  ) +
  scale_x_continuous(expand = c(0,0), limits = c(0, 0.55)) +
  scale_y_continuous(expand = c(0,0), limits = c(550,1400)) +
  coord_cartesian(clip = 'off') +
  theme_classic() +
  theme(text = element_text(size=14),
        axis.line.y.right = element_line(color = "black"),
        axis.line.x.top = element_line(color = "black"),
        panel.border = element_rect(colour = "black", fill=NA))  

ggplot(ch_max_sca_wc_bs_snotel, aes(x = swe_m*1000, y = sca_km_2)) +
  geom_point(aes(color = snotel_station), size = 2) +
  labs(
    x = "SNOTEL SWE (mm)",
    y = bquote("Snow Covered Area " (km^2)),
    title = "Beaver Spring Max SNOTEL SWE and Chuska SCA",
    color = "SNOTEL Station"
  ) +
  scale_x_continuous(expand = c(0,0), limits = c(0, 450)) +
  scale_y_continuous(expand = c(0,0), limits = c(550,1400)) +
  coord_cartesian(clip = 'off') +
  theme_classic() +
  theme(text = element_text(size=14),
        axis.line.y.right = element_line(color = "black"),
        axis.line.x.top = element_line(color = "black"),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.position = "bottom")  


```

MAX snow course SWE and max sca Chuska

```{r,echo = FALSE}

bs_wc_snowcourse <- snow_course %>% 
  filter(station_name %in% c("Beaver Spring", "Whiskey Creek")) %>% 
  drop_na() %>% 
  group_by(waterYear, station_name) %>% 
  top_n(1, swe_mm) %>% 
  slice(1)

ch_sca_snowcourse <- bs_wc_snowcourse %>% 
  left_join(chuska_max_week_sca, by = "waterYear")

ggplot(ch_sca_snowcourse, aes(x = swe_mm, y = sca_km_2)) +
  geom_point(aes(color = station_name), size =2) +
  labs(
    x = "Snowcourse SWE (mm)",
   y = bquote("Chuska Snow Covered Area " (km^2)),
   color = "Snowcourse Station",
   title = "Chuska Max SCA and Snowcourse Max SWE"
  ) +
  theme_classic() +
  theme(text = element_text(size=14),
        axis.line.y.right = element_line(color = "black"),
        axis.line.x.top = element_line(color = "black"),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.position = "bottom")  

plot(lm(ch_sca_snowcourse$sca_km_2 ~ ch_sca_snowcourse$swe_mm))
cor.test(ch_sca_snowcourse$sca_km_2, ch_sca_snowcourse$swe_mm, method = "spearman")
  

```

